insert into companies(slug,name_ko,enabled) values('apr','에이피알',true),('com2us','컴투스',false);
insert into brands(company_id,canonical_name,aliases) select id,'medicube','["메디큐브"]' from companies where slug='apr';
insert into categories(ref,marketplace,canonical_type,review_note) values('US_beauty','US','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('US_skincare','US','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('GB_beauty','GB','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('GB_skincare','GB','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('DE_beauty','DE','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('DE_skincare','DE','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('FR_beauty','FR','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('FR_skincare','FR','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('IT_beauty','IT','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('IT_skincare','IT','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('ES_beauty','ES','beauty','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into categories(ref,marketplace,canonical_type,review_note) values('ES_skincare','ES','skincare','2026-09-06 실제 공급원·샘플·노드 증거 미제공');
insert into sources(ref,kind,display_name,mode) values('amazon_primary','amazon_rank','Amazon 승인 자료','unconfigured');
insert into sources(ref,kind,display_name,mode) values('customs_primary','trade_statistics','관세청 수출입','official_api_pending');
insert into sources(ref,kind,display_name,mode) values('dart_primary','filing','OpenDART','official_api_pending');
insert into sources(ref,kind,display_name,mode) values('research_kwon_woojeong','research_channel','권우정','link_only');
insert into sources(ref,kind,display_name,mode) values('research_kim_myeongju','research_channel','김명주','link_only');
insert into source_permissions(source_id) select id from sources;
insert into source_capabilities(source_id,marketplace,data_kind,period_type,category) select s.id,c.marketplace,'amazon_rank','day',c.canonical_type from sources s cross join categories c where s.ref='amazon_primary';
