-- M0-M2 only. Apply to a Supabase PostgreSQL project; no real data in migrations.
create schema if not exists private;
revoke all on schema private from public;
create table private.memberships(user_id uuid primary key references auth.users(id), role text not null check(role in ('admin','viewer')), active boolean not null default true, invited_by uuid, created_at timestamptz not null default now());
create table private.invites(id uuid primary key default gen_random_uuid(), email_normalized text unique not null check(email_normalized=lower(trim(email_normalized))), role text not null default 'viewer' check(role='viewer'), expires_at timestamptz not null, invited_by uuid not null, redeemed_by uuid, created_at timestamptz not null default now());
create table private.audit_logs(id uuid primary key default gen_random_uuid(), actor uuid, action text not null, target text not null, before_hash text, after_hash text, occurred_at timestamptz not null default now());
create table public.companies(id uuid primary key default gen_random_uuid(), slug text unique not null, name_ko text not null, stock_code text, dart_corp_code text check(dart_corp_code ~ '^[0-9]{8}$'), enabled boolean not null default false);
create table public.brands(id uuid primary key default gen_random_uuid(), company_id uuid not null references companies, canonical_name text not null, aliases jsonb not null default '[]', unique(company_id,canonical_name));
create table public.product_families(id uuid primary key default gen_random_uuid(), brand_id uuid not null references brands, name text not null, product_type text not null check(product_type in ('cosmetics','device','bundle','other')));
create table public.listings(id uuid primary key default gen_random_uuid(), marketplace text not null check(marketplace in ('US','GB','DE','FR','IT','ES')), asin text not null check(asin ~ '^[A-Z0-9]{10}$'), title text not null, parent_asin text check(parent_asin ~ '^[A-Z0-9]{10}$'), unique(marketplace,asin));
create table public.listing_assignments(id uuid primary key default gen_random_uuid(), listing_id uuid not null references listings, product_family_id uuid not null references product_families, approval text not null check(approval in ('approved','candidate','rejected')), valid_from date not null, recorded_at timestamptz not null default now(), version integer not null check(version>0), evidence_ref text not null, approved_by uuid not null, unique(listing_id,version));
create table public.categories(id uuid primary key default gen_random_uuid(), ref text unique not null, marketplace text not null check(marketplace in ('US','GB','DE','FR','IT','ES')), canonical_type text not null check(canonical_type in ('beauty','skincare')), source_node_id text, path text, listing_url text, version integer not null default 1, verification_status text not null default 'pending' check(verification_status in ('pending','verified','not_equivalent')), review_note text not null, reviewed_at timestamptz not null default now(), unique(marketplace,canonical_type,version), check(verification_status <> 'verified' or (source_node_id is not null and path is not null and listing_url is not null)));
create table public.sources(id uuid primary key default gen_random_uuid(), ref text unique not null, kind text not null, display_name text not null, base_url text, mode text not null default 'unconfigured', enabled boolean not null default false, allowed_hosts text[] not null default '{}', status text not null default 'configuration_pending', last_checked_at timestamptz);
create table public.source_permissions(source_id uuid primary key references sources, collect_allowed boolean not null default false, store_raw_allowed boolean not null default false, store_derived_allowed boolean not null default false, share_allowed boolean not null default false, export_allowed boolean not null default false, ai_allowed boolean not null default false check(ai_allowed=false), evidence_ref text, reviewed_by uuid, reviewed_at timestamptz, expires_at timestamptz, raw_ttl integer not null default 1 check(raw_ttl between 1 and 14), derived_ttl integer not null default 730 check(derived_ttl>0));
create table public.source_capabilities(id uuid primary key default gen_random_uuid(), source_id uuid not null references sources, marketplace text, data_kind text not null, period_type text, category text, supported boolean, evidence_ref text);
create table public.import_batches(id uuid primary key default gen_random_uuid(), uploader_id uuid not null, source_id uuid not null references sources, file_hash text not null, filename text not null, object_key text, schema_version text not null default '1.0', state text not null default 'uploaded' check(state in ('uploaded','parsed','validated','needs_review','approved','committed','failed')), errors jsonb not null default '[]', warnings jsonb not null default '[]', summary jsonb not null default '[]', created_at timestamptz not null default now(), unique(source_id,file_hash));
create table private.import_payloads(batch_id uuid primary key references public.import_batches, content text not null, expires_at timestamptz not null);
create table public.job_requests(id uuid primary key default gen_random_uuid(), kind text not null check(kind in ('validate_import','commit_import')), requested_by uuid not null, batch_id uuid not null references import_batches, state text not null default 'queued' check(state in ('queued','running','done','failed')), requested_at timestamptz not null default now(), started_at timestamptz, lease_until timestamptz, attempts integer not null default 0, unique(kind,batch_id));
create table public.collection_runs(id uuid primary key default gen_random_uuid(), source_id uuid references sources, job_id uuid references job_requests, started_at timestamptz not null default now(), finished_at timestamptz, status text not null, counts jsonb not null default '{}', parser_version text not null default 'amazon_csv_v1');
create table public.source_objects(id uuid primary key default gen_random_uuid(), source_id uuid not null references sources, object_key text unique not null, sha256 text not null, bytes bigint not null, expires_at timestamptz not null, visibility text not null default 'admin' check(visibility='admin'), deleted_at timestamptz);
create table public.amazon_snapshots(id uuid primary key default gen_random_uuid(), source_id uuid not null references sources, run_id uuid references collection_runs, category_id uuid not null references categories, snapshot_ref text not null, observed_at timestamptz, kst_date date not null, time_precision text not null check(time_precision in ('date','timestamp')), slot text not null, expected_count integer not null default 100 check(expected_count=100), actual_count integer not null check(actual_count between 1 and 100), completeness text not null check(completeness in ('complete','partial')), content_hash text not null, revision integer not null, first_seen_at timestamptz not null default now(), recorded_at timestamptz not null default now(), backfill boolean not null default false, expires_at timestamptz not null, unique(source_id,category_id,content_hash), check((time_precision='date' and observed_at is null) or (time_precision='timestamp' and observed_at is not null)), check(completeness<>'complete' or actual_count=100));
create table public.amazon_rank_entries(snapshot_id uuid not null references amazon_snapshots, position integer not null check(position between 1 and 100), listing_id uuid not null references listings, raw_brand text, observed_title text not null, source_url text not null, primary key(snapshot_id,position), unique(snapshot_id,listing_id));
create table public.amazon_product_observations(listing_id uuid not null references listings, snapshot_id uuid not null references amazon_snapshots, price numeric check(price>=0), currency text check(currency in ('USD','GBP','EUR')), rating numeric check(rating between 0 and 5), review_count bigint check(review_count>=0), availability text, review_scope text, primary key(listing_id,snapshot_id));
create table public.snapshot_selections(id uuid primary key default gen_random_uuid(), marketplace text not null, category_id uuid not null references categories, kst_date date not null, slot text not null, snapshot_id uuid not null references amazon_snapshots, selected_at timestamptz not null default now(), supersedes_id uuid references snapshot_selections, reason text not null, selected_by uuid);
create index selections_lookup on snapshot_selections(category_id,kst_date,slot,selected_at desc);
create index snapshots_lookup on amazon_snapshots(category_id,kst_date,first_seen_at);
create index assignments_lookup on listing_assignments(listing_id,recorded_at desc,version desc);
create index entries_listing on amazon_rank_entries(listing_id,snapshot_id);
-- Metrics are recomputed in bounded RPCs against immutable evidence and mapping history.
-- M3/M4 entities intentionally remain future migrations, not pretend working modules.
